name: telemoni
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.7+5
  permission_handler: ^10.2.0
  cupertino_icons: ^1.0.6
  http: ^0.13.4
  shared_preferences: ^2.0.13
  provider: ^6.0.0
  flutter_secure_storage: ^8.0.0
  image: ^3.0.1
  firebase_auth: ^5.2.0
  firebase_core: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  share_plus: ^6.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/profile.png
    - assets/telegram.png
    - assets/zoom.png
    - assets/lock.png
    - assets/404.jpg
    - assets/clock.png
